// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4yk4eezVftDnAM4Hj53thIt3c_QjnvEs',
    appId: '1:234334817589:web:dcbc8f197605d4c7c6d07c',
    messagingSenderId: '234334817589',
    projectId: 'cutpulse-eac48',
    authDomain: 'cutpulse-eac48.firebaseapp.com',
    databaseURL: 'https://cutpulse-eac48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cutpulse-eac48.firebasestorage.app',
    measurementId: 'G-L59FXVMTPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PUT_YOUR_OWN_KEY!',
    appId: '1:234334817589:android:ff8d433531e0b96cc6d07c',
    messagingSenderId: '234334817589',
    projectId: 'cutpulse-eac48',
    databaseURL: 'https://cutpulse-eac48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cutpulse-eac48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQkC18x27haBiRMB9NyxqmUFZla4UiWU0',
    appId: '1:234334817589:ios:ac07a8d844475522c6d07c',
    messagingSenderId: '234334817589',
    projectId: 'cutpulse-eac48',
    databaseURL: 'https://cutpulse-eac48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cutpulse-eac48.firebasestorage.app',
    iosBundleId: 'com.example.cutpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQkC18x27haBiRMB9NyxqmUFZla4UiWU0',
    appId: '1:234334817589:ios:ac07a8d844475522c6d07c',
    messagingSenderId: '234334817589',
    projectId: 'cutpulse-eac48',
    databaseURL: 'https://cutpulse-eac48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cutpulse-eac48.firebasestorage.app',
    iosBundleId: 'com.example.cutpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4yk4eezVftDnAM4Hj53thIt3c_QjnvEs',
    appId: '1:234334817589:web:6812b20f82af0cbac6d07c',
    messagingSenderId: '234334817589',
    projectId: 'cutpulse-eac48',
    authDomain: 'cutpulse-eac48.firebaseapp.com',
    databaseURL: 'https://cutpulse-eac48-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cutpulse-eac48.firebasestorage.app',
    measurementId: 'G-DN1FE1M54H',
  );

}
